### ISSUE TITLE
Creating the new themes after command themes-cli preview

### ISSUE THREAD

**Issue by AntonVasylchenko** [zidsa/zid-theme-npm#22]
After each successful “themes-cli preview” command, a new theme is created in the store. This theme does not have all the settings and you need to constantly fill them in again. And this happens after each command is executed

https://www.awesomescreenshot.com/video/34086898?key=ec84f680b92d578e98b9bc4b3e0e9bca

**Comment by iahmadmahr** [comment]
Hello @AntonVasylchenko  our team released an update yesterday day it should be fixed now, please confirm.

thanks for reporting this to us and keep up the good work.

Kind Regards

**Comment by AntonVasylchenko** [comment]
It still doesn't work correctly, the update command creates a new theme with empty settings.

**Comment by pdj1985** [comment]
Hello @AntonVasylchenko the change will be deployed in the new version 1.0.6 on monday, it will include an extra parameter --theme_name 'theme name' for the update, it will look like:

`themes-cli preview --store_email dev_store@zam-partner.email --code 'theme name'`

I will notify it here. Thanks

**Comment by AntonVasylchenko** [comment]
@pdj1985 
Hi, when will version 1.0.6 be released?

**Comment by pdj1985** [comment]
@AntonVasylchenko hopefully today, tomorrow max.

**Comment by pdj1985** [comment]
@AntonVasylchenko it's release, [v1.1.0](https://www.npmjs.com/package/@zidsa/themes-cli). Please check the new documentation for preview.
